version: "3"
services:
    database:
      container_name: mysql
      image: mysql:5.7
      environment:
        MYSQL_HOST: "localhost"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "12345678"
        MYSQL_DATABASE: "db"
        REACT_APP_SERVER_PORT: "8080"
      ports:
        - "6603:3306"
      restart: unless-stopped
      volumes:
        - ./data:/var/lib/mysql
        - ./db/user.sql:/docker-entrypoint-initdb.d/user.sql
    phpmyadmin:
      container_name: phpmyadmin
      depends_on:
        - database
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: mysql
      links:
        - database:mysql
      ports:
        - "5001:80"
      restart: always
    frontend:
        container_name: web
        build:
          context: ./client
          dockerfile: Dockerfile
        image: resume/web
        depends_on:
          - backend
        environment: 
          REACT_APP_BACKEND_HOST_IP: backend
          REACT_APP_SERVER_PORT: "8080"
          REACT_APP_NODE_PATH: "src"
        ports:
          - "80:3000"
        volumes:
          - ./client:/usr/src/app/
          - /usr/src/app/node_modules
        links:
          - backend
    backend:
        container_name: server
        build:
          context: ./server
          dockerfile: Dockerfile
        image: resume/server
        depends_on:
          - database
        environment:
          MYSQL_USER: "admin"
          MYSQL_PASSWORD: "12345678"
          MYSQL_DATABASE: "db"
          REACT_APP_SERVER_PORT: "8080"
          MYSQL_HOST_IP: database
        ports:
          - "8080:8080"
          - "3306:3306"
        volumes:
          - ./server:/usr/src/app
          - /usr/src/app/node_modules
        links:
          - database