version: "3"
services:
    frontend:
        container_name: web
        build:
          context: ./client
          dockerfile: Dockerfile
        image: resume/web
        environment:
          DANGEROUSLY_DISABLE_HOST_CHECK: "true"
          REACT_APP_NODE_PATH: "src"
          HTTPS: "true"
          SSL_CRT_FILE: "/usr/src/app/ssl/certificate.crt"
          SSL_KEY_FILE: "/usr/src/app/ssl/certificate.key"
        ports:
          - "443:3000"
        volumes:
          - ./client:/usr/src/app/
          - /usr/src/app/node_modules
          - ./ssl:/usr/src/app/ssl/
